NovaSector/NovaSector

- _maps/map_files/generic/CentCom_skyrat_z2.dmm
- modular_nova/modules/ghostcafe/code/ghost_cafe_items.dm
- modular_nova/modules/ghostcafe/code/ghost_role_spawners.dm
- modular_nova/modules/ghostcafe/code/ghostcafeturf.dm
- modular_nova/modules/mapping/code/areas/centcom.dm
- tgstation.dme
Ghost cafe changes - new areas, catwalker zone and ashwalker zone.
Also vox proofs the vox box.
I just personally want a sauna and hot tub in there to be honest. There's also some places for ice cats and ashwalkers to hang out too, so that's cool. 
<details>
</details>
:cl:
add: Added new areas to the ghost cafe, including a ashwalker and icewalker zones.
/:cl:
> Ghost Cafe Re-model

- tgui/packages/tgui/interfaces/NifPanel.jsx
This fixes a silly error that was introduced when we where updating to react
Working UI is nice, I like when my UI works
<details>
</details>
:cl:
fix: NIFsoft settings panel now works once again
/:cl:
> Fixes Niftsoft Settings Panel

- code/modules/mob/living/carbon/carbon_defense.dm
- code/modules/vending/_vending.dm
- modular_nova/modules/ashwalkers/code/buildings/ash_tendril.dm
- modular_nova/modules/modular_items/lewd_items/code/lewd_arousal/status_effects/climax.dm
- tgui/packages/tgui/interfaces/ClockworkSlab.jsx
- tgui/packages/tgui/interfaces/NifPanel.jsx
This PR is a just a junkdrawer of fixes. Notably converts clockwork cultist ui to useState, which TG is going to be swapping to soon. Also fixed something that was lost in a vending machine refactor 6 months ago.
Bugfixes/code improvement
<details><summary>Working</summary>
</details>
:cl:
fix: fixes an instance of the quick reflexes trait not being honored
fix: fixes ashwalker sacrifice immediately gibbing revived lizards
del: vending machines will no longer squash mobs
/:cl:
> General code maint + fixes

- modular_nova/modules/colony_fabricator/code/colony_fabricator.dm
It's still gonna fail tests after this but at least it wont be for reasons caused by me
Yeah
<details>
🖕
</details>
The changelog doesn't need to worry about this one
> Fixes #476 because it keeps telling me i cant access pushing to the branch

- _maps/map_files/VoidRaptor/VoidRaptor.dmm
https://github.com/NovaSector/NovaSector/pull/670
https://github.com/NovaSector/NovaSector/runs/21389343509
Space bitrunners no more.
<details>
</details>
> VoidRaptor small fix - Deletes Space Bitrunner Den

- modular_nova/modules/customization/modules/surgery/organs/genitals.dm
Fixes typo involving the description of a certain state of a certain organ.
I don't think there should be particles involved with that, that sounds uncomfortable.
<details>
</details>
:cl: Thlumyn
spellcheck: fixed typo describing male organ
/:cl:
> Fix typo in description of an organ

- _maps/map_files/VoidRaptor/VoidRaptor.dmm
Changes access on void raptor windoors into animal pens so that they open on maints_access access instead of maintenance.
Fixes: #1048 
<details>
</details>
:cl: Thlumyn
fix: animal pen doors on void raptor now open with maints access
/:cl:
> Fix animal pen doors on void raptor

- modular_nova/modules/customization/modules/mob/living/carbon/human/human.dm
- modular_nova/modules/customization/modules/mob/living/carbon/human/species/ghoul.dm
Small change to ghoul code to try and fix a bug where they were not able to reattach their limbs
Fixes #1197 
<details>
</details>
:cl:
fix: ghouls can once again replace their limbs with meat slabs
/:cl:
> Ghouls can (once again) replace their limbs with meat slabs

- modular_nova/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
i can't believe you've done this
> donator item spellcheck heeheehoohoo

- modular_nova/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
at request of dono item holder
> adds ckey to dono item

- modular_nova/master_files/code/modules/client/preferences/middleware/food.dm
This should probably fix a runtime that is causing an issue in food perfs. this var wasn't needed anymore and shouldn't be here
Less bugs
Not really player facing, no need for a changelog here
> Removes Unused variable pass to proc in food perfs

- modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
Missed a line that starts a timer to disable the shuttle, given the rest of the code that manages it after that no longer exists this removes the call.
<details>
</details>
:cl:
/:cl:
> [S] removes the shuttle call for the Wireweed

- modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
Reverts NovaSector/NovaSector#1547
> Revert "[S] removes the shuttle call for the Wireweed"

- modular_nova/modules/alternative_job_titles/code/alt_job_titles.dm
Tin.
Be nice to new chefs.
:cl:
add: Adds a 'Junior chef' alt-title for chefs
/:cl:
> Adds a 'Junior chef' alt-title for chefs

- modular_nova/modules/faction/maps/shuttles/tradership_faction.dmm
- modular_nova/modules/tarkon/code/machines/smes.dm
This should help alleviate power issues with some of our mapped SMES
less power issues the better
<details>
</details>
:cl:
fix: Tarkon roundstart SMES should start with full power
/:cl:
> SMES Fixes for Tarkon and trader ship

- _maps/RandomRuins/SpaceRuins/nova/des_two.dmm
Some small quality of life changes for DS-2, mostly some stuff I overlooked when I was re-doing DS-2/Interdyne for Skyrat last year.
This adds:
- A defib in a medical crate in DS-2's cargo bay.
- Tier 4 part boxes instead of tier 1s in their R&D area, along with a bluespace RPED.
- A few extra building materials.
- Windoors around the botany trays in DS-2's botany area.
Here's my reasoning for each change one by one below.
<details>
**Defib:**
This should be used to revive folks in emergencies as Interdyne might not always be available. They can print these already, but they should really start with one for niche scenarios where someone might die early into the round before science has researched medical tech. Having to potentially wait 20-30 minutes or more to get revived because the …
> [Modular] DS-2 QoL changes

- code/modules/cargo/bounties/mining.dm
Not player facing as this will make the Changelog match up with what it is supposed to be, i just did a dumb while sleepy and broke the mirror
> Fixes a TG mirror i accidentialy Broke

- modular_nova/modules/emotes/code/laugh_datums.dm
Lets people have the option to laugh for a lizard
Lizards laugh too
<details>
https://github.com/NovaSector/NovaSector/assets/2568378/c8eecc2d-9e5b-49b5-bf50-dbc1e1e376d1
</details>
:cl:
add: Lizard laugh is now a selectable laugh in the character creator
/:cl:
> [Modular] Allows the new TG lizard laugh to be selected as a character laugh

- modular_nova/modules/digitigrade_cybernetics/code/mechfabricator_designs.dm
- modular_nova/modules/tesh_augments/code/mechfabricator_designs.dm
https://github.com/Skyrat-SS13/Skyrat-tg/pull/27605
in essence, medical should be able to actually print these I think?
:cl:
fix: moved raptor and digi cybernetics' categories
/:cl:
> [Minor fix] Raptor/Digi cybernetics recategorization

- code/__DEFINES/admin_verb.dm
- code/controllers/configuration/entries/general.dm
- code/controllers/subsystem/ipintel.dm
- code/modules/client/client_procs.dm
> [MISSED MIRRORS] General IP intel tweaks (#82904) + fix ipintel caching to db not working. (#83046)

- modular_nova/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
With our powers combined we can both make cool cybergoths. Shares my donator item with them, shares theirs with mine.
https://www.youtube.com/watch?v=xczTKlRxBdU
> Trades Donator Items w/ My New Friend

- modular_nova/modules/polarized_windows/polarization_controller.dm
Forgot to update the arguments for the signal, whoops
(I didn't)
:cl:
fix: window polarizers can be linked again
/:cl:
> Fix window polarizers

- _maps/map_files/NSVBlueshift/Blueshift.dmm
- _maps/map_files/Ouroboros/Ouroboros.dmm
- _maps/map_files/VoidRaptor/VoidRaptor.dmm
This will fix the modular map changes needed for #3441
> Fixes modular maps for nearspace unit tests #3441

- _maps/map_files/Ouroboros/Ouroboros.dmm
My hubris got the better of me.
> Fixes the Ouroboros CI issue

- _maps/map_files/SerenityStation/SerenityStation.dmm
scrubs `piping_layer` from serenity station
Not player facing
> Fix master CI

- code/modules/mob/emote.dm
pretty self explanatory, im not very smart, thank you for your understanding
<details>
</details>
:cl:
fix: the space-ban on station-side screaming has been lifted, We hope you enjoyed the peace and quiet.
/:cl:
> Fix scream emotes

- modular_nova/modules/colony_fabricator/sound/attributions.txt
- modular_nova/modules/gun_safety/readme.md
- modular_nova/modules/imported_vendors/readme.md
- modular_nova/modules/manufacturer_examine/readme.md
- modular_nova/modules/novaya_ert/readme.md
- modular_nova/modules/primitive_cooking_additions/readme.md
- modular_nova/modules/primitive_structures/readme.md
- modular_nova/modules/wargame_projectors/readme.md
- modular_nova/modules/xenos_nova_redo/readme.md
Since I still don't want to be contracted by or associate with you people any further, I'm removing any mention of me from any module readmes or attributions. Don't credit me, don't call me, because I'm not picking up the phone for this shit anymore.
I need to take a long vacation to recover from the back injuries I got from both carrying nova's feature development for half a year then getting kicked down a flight of stairs by the hosts, and I don't want anyone mistakenly contacting me for help on something I'm not a part of anymore.
Since when have you ever actually been concerned.
No.
> removes mentions of me from module readme files and attributions

- modular_nova/master_files/code/datums/quirks/neutral_quirks/lungs.dm
- modular_nova/master_files/code/modules/mob_spawn/mob_spawn.dm
- modular_nova/modules/borgs/code/robot_items.dm
- modular_nova/modules/cryosleep/code/cryopod.dm
- modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/genitals.dm
- modular_nova/modules/customization/modules/mob/living/carbon/human/species.dm
- modular_nova/modules/customization/modules/surgery/organs/nif.dm
- modular_nova/modules/loadouts/loadout_items/loadout_datum_neck.dm
- modular_nova/modules/loadouts/loadout_ui/loadout_outfit_helpers.dm
- modular_nova/modules/modular_persistence/code/modular_persistence.dm
- modular_nova/modules/synths/code/surgery/mechanic_steps.dm
- modular_nova/modules/synths/code/surgery/robot_brain_surgery.dm
- modular_nova/modules/synths/code/surgery/robot_chassis_restoration.dm
- modular_nova/modules/synths/code/surgery/robot_healing.dm
Just fixes some runtimes. Many are non player facing (for now!)
There's sort of a lot of these and I'm not sure how practically I can explain all of them- there's more or less one runtime per commit, though. 
bugn't
<details>
Just one of the player facing ones- if your loadout case can't spawn in your hands, things still get colored.
</details>
:cl:
fix: venus human traps properly despawn when used
fix: loadout briefcases will still customize your items if they can't spawn in your hand
/:cl:
> Assortment of runtime fixes

- .github/CODEOWNERS
Not player facing. Adding myself into the codeowners for maps.
maptainer stuff
> [NO GBP] Add myself to maps codeowners.

- _maps/shuttles/nova/cargo_nova_delta.dmm
Button ID needs to equal the door ID, SQN. You know this, you moron.
p.s. make sure you test both shuttle styles next time. 
Fix.
<details>
</details>
:cl:
fix: doors for the delta style shuttle work again.
/:cl:
> [NO GBP] Fixes delta cargo shuttle

- modular_nova/modules/deforest_medical_items/code/storage_items.dm
they now say they have sugar in them, that's all
they prolly shouldn't lie about something that rolls as an allergy
:cl:
fix: Amollin now actually tells you what's in it.
/:cl:
> fixes those silly little amollin pills lying to us

- _maps/RandomRuins/IceRuins/nova/icemoon_duo_hermit.dmm
- _maps/RandomRuins/LavaRuins/nova/lavaland_duo_hermit.dmm
- config/iceruinblacklist.txt
- config/lavaruinblacklist.txt
- modular_nova/modules/mapping/code/icemoon.dm
- modular_nova/modules/mapping/code/lavaland.dm
New hermits houses for duo. Maps by Swing.
Together is better.
:cl:FeenieRU, Swing
map: Added duo-variants of hermits templates.
/:cl:
> Duo Hermits

- _maps/RandomRuins/LavaRuins/nova/lavaland_duo_hermit.dmm
overlooked this in my final review
<details>
</details>
:cl:
/:cl:
> Replaces the black raptor spawn with red in the hermit spawner

- modular_nova/master_files/code/datums/components/damage_tracker.dm
Stores these as weakrefs instead. Hopefully will fix (possibly) https://github.com/NovaSector/NovaSector/issues/1850
Nothing player-facing
> Fixes a potential source of brain trauma hard dels

- modular_nova/modules/ai_uplink_upload/the_thing.dm
Yep, that's literally it. No reason to have a non-static list here and I am just noticing it after pressing the big green button on the PR that added this.
N/A
> Makes this list static

- _maps/map_files/NSVBlueshift/Blueshift.dmm
Its all in the name
people wont get stuck
<details>
https://github.com/user-attachments/assets/d2b36afa-04bc-45f7-937d-4f4bdcebb838
</details>
:cl:
fix: Fixes the blueshift AI transit tube properly be able to step back in.
/:cl:
> Fixes blueshift AI transit tube from people getting stuck

- modular_nova/master_files/code/modules/mob/living/examine_tgui.dm
- modular_nova/modules/character_directory/code/character_directory.dm
- tgui/packages/tgui/interfaces/ExaminePanel.jsx
- tgui/packages/tgui/interfaces/NovaCharacterDirectory.jsx
Tin, this was not quite right.
<details>
</details>
:cl:
fix: fixes veteran status not displaying correctly in examine panel for some people
/:cl:
> Fixes potential issues with veteran status display in examine panel

- modular_nova/master_files/code/modules/mob/living/examine_tgui.dm
- modular_nova/modules/character_directory/code/character_directory.dm
This time for the character directory only. The char directory keeps the previous person's vars in scope apparently, which normally is not an issue because it just ends up reading the prefs from the next person.
I wish I noticed this 7 hours ago
> Another fix for veteran status

- _maps/RandomZLevels/heretic.dmm
This should not be there, replaces it with some other goodies.
> Replaces a debug item from the new away mission

- code/modules/client/preferences/clothing.dm
- code/modules/jobs/job_types/_job.dm
test your code dorks 
removes the free makarov and 3 magazines this guncase gave you
<details>
</details>
:cl:
fix: fixes the loadout guncase from giving you a free makarov and ammo and replaces it with the right guncase
/:cl:
> Fixes the guncase option

- modular_nova/modules/character_directory/code/character_directory.dm
Tin, just fixes a quick runtime that I saw happening with the character directory.
Nothing anyone'll notice probably.
> Fixes a runtime in char directory

- code/modules/art/paintings.dm
> removes hello

- _maps/map_files/generic/CentCom_nova_z2.dmm
faster startup time, a whole `right now` seconds saved
<details>
refer PR body for proof
</details>
:cl:
fix: Interlink staffing changes: fired Breaks-The-PRs and hired Fixes-The-ATs instead
/:cl:
> Interlink AT fix

- _maps/nova/automapper/templates/catwalkstation/catwalkstation_arrivals.dmm
docking id, screen
<details>
</details>
:cl:
fix: catwalk - arrivals now has the shuttle timer display.
/:cl:
> [no gbp] Catwalk - one last arrivals fix.
