NovaSector/NovaSector

.github/workflows/compile_changelogs.yml
Uses the right kind of access token so that the Compile Changelogs action can work properly.
Not player-facing.
=> Fixes Compile Changelog by making it use GITHUB_TOKEN instead of a secret token

modular_nova/modules/food_replicator/code/clothing.dm, modular_nova/modules/novaya_ert/code/police_outfit.dm
Fixes https://github.com/NovaSector/NovaSector/issues/120
These for some reason are a cloak that is wearable in both the neck slot and suit slot. The issue is that cloaks don't have an `allowed` var set to anything.
Defines the allowed items for this specific type of cloak, the only one of its kind. It can hold the same things as a leather jacket.
The NRI version is able to hold some extra police items (ammo and restraints). 
Fixes a special case oversight
<details>
</details>
:cl:
fix: colonial cloaks and imperial police cloaks can now carry suit storage items when worn in the suit slot.
/:cl:
=> [MODULAR] Fixes colonial cloaks not being able to hold any suit storage items

code/modules/client/preferences.dm, modular_nova/master_files/code/modules/mob/login.dm, modular_nova/modules/player_ranks/code/preferences.dm, modular_nova/modules/player_ranks/code/subsystem/player_ranks.dm, tgstation.dme
Fixes an issue introduced by https://github.com/Skyrat-SS13/Skyrat-tg/pull/18946 where players on the server donator list are marked as BYOND membership holders.
This adds a variable, donator_status that correctly holds a player's donator status to the server and unlocks the associated content.
We're all thankful for the work Lummox puts in to keep BYOND alive and he doesn't ask for much. Circumventing the BYOND membership check in exchange for a donation to the server instead is hopefully not intended behavior.
<details>
</details>
:cl: LT3
fix: Fixed BYOND membership status being available to non-BYOND members
/:cl:
=> Fix BYOND membership status available to non-members

modular_nova/modules/opposing_force/code/opposing_force_datum.dm, tgui/packages/tgui/interfaces/OpposingForcePanel.jsx
See screenshots for the before/after. Also per request makes it so that when you send a chat message to a player as an admin using the opfor panel, it will consider you as handling the opfor (if no one else is).
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
:cl:
admin: opfor panel 'approve objective' button is no longer annoyingly in the way of the objective title text
qol: when you send a message as an admin via the opfor panel and no one is handling the opfor, it will automatically mark you as handling it
/:cl:
=> [MODULAR] Changes opfor 'approve/deny' objective buttons, opfor chat qol

code/_onclick/hud/rendering/plane_master_group.dm, code/_onclick/hud/rendering/render_plate.dm
Fixes https://github.com/tgstation/tgstation/issues/79954
Turns out the cause of cameras breaking was something weird with how
Byond determined the CENTER location for screen_locs on secondary popup
maps like cameras and the spyglass. This can be remedied by manually
using the LEFT,TOP position for the plane relays. However LEFT,TOP
breaks the views for clients 1614 and below so I included a jank
solution that should allow any client up to this point have the screen
displayed correctly
Cameras working passed 1614 means you can update the server. At some
point I suspect Lummox will fix the CENTER position on secondary maps
and when that happens it will likely break the current fix.
:cl:
fix: popup screen locs will work on clients >1614. Security cameras and
Spyglass will work
/:cl:
=> [MISSED MIRROR] Fixes Cameras views on clients 515.1615 or greater (#80818)

modular_nova/modules/tableflip/code/flipped_table.dm
Fixes https://github.com/NovaSector/NovaSector/issues/570
That's it really!
Fixes an oversight/potential material exploit with the tableflipping system.
<details>
<summary>Holographic tables will now obey the laws of physics and cannot be dismantled</summary>
</details>
:cl:
fix: fixes being able to flip holographic tables into reality and harvest them for materials
/:cl:
=> Fixes being able to flip holographic tables into reality and harvest them for materials

_maps/RandomRuins/SpaceRuins/nova/cargodiselost.dmm
Adds a flat-packed Rapid Construction Fab, and a Colonial Supply board to the freighter, alongside a few missing lights and vents.
The lights and vents are primarily just fixes that I missed while putting the remake together initially. That being said, the RCF and Colonial Supply machines both add a little bit more flexibility and independence to the role.
Not to mention, instead of relying on solars, the crew can fashion out some other makeshift solutions with the machines the RCF can print! Overall, I'm just hoping to improve the QoL of the role somewhat, and make rounds feel more varied for the freighter crew.
Included below is a screenshot of one of the areas with some added lights, and vents, and another one showing the RCF set up in the Freighter's engineering bay.
<details> …
=> More Freighter Fixes and Improvements

code/modules/mob/living/carbon/human/human_update_icons.dm
Port of https://github.com/Skyrat-SS13/Skyrat-tg/pull/26507, made here in the spirit of fairness
A bit of a technical PR..
Basically, limbs have bodytypes. Ex. tesh limbs have BODYTYPE_CUSTOM. Digi legs have BODYTYPE_DIGITIGRADE. If a mob had BODYTYPE_DIGITIGRADE, we wouldnt even consider CUSTOM, despite the fact that the clothing might not even support digi, meaning we can safely use custom. This allows tesh to have digi legs and wear things like winter coats without the game breaking.
bugs bad
<details>
</details>
:cl:
fix: Characters with multiple bodytypes are no longer forced to bear broken clothing sprites
/:cl:
=> [SEMIMODULAR] Fixes multi-bodytype characters (digitigrade, species custom) only having digi apply when custom could be applied

code/game/machinery/doors/firedoor.dm
[TG PR #72887](https://github.com/tgstation/tgstation/pull/72887)
I think it's because of null gasmixtures being handed back in this proc.
It'd match with the alert state we get
If it isn't then I want to know, and this is a pretty good way of going
about that whole process
--------
=> [MISSED MIRROR] Potentially fixes roundstart firelock hell (#72887)

modular_nova/master_files/code/modules/mob_spawn/mob_spawn.dm
It's always bothered me that you couldn't search a ghost role player in the player panel by their job's title, so I fixed it so that now, you can do just that!
It makes it easier for staff to look up certain roles by name rather than by player name.
<details>
</details>
fix: Humanoid ghost roles now receive their job title on their mob, when that was previously not the case.
admin: Humanoid ghost roles can now be searched by job title in the Player Panel directory (and will show up everywhere else that displays the job title).
/:cl:
=> Ghost roles now have their job title set properly on spawn

code/game/objects/items/tcg/tcg_machines.dm, modular_nova/master_files/code/modules/mob/living/emote_popup.dm, modular_nova/modules/gunpoint/code/gunpoint_datum.dm, modular_nova/modules/mapping/code/planet_turfs.dm
This sets all of the instances of mouse_opacity in modular files to use the define for mouse opacity to remain consistent with other instances of mouse opacity being set in TG rather than having ours as a static number
Consistency across modular files is good
Going to skip this for this PR as its just minor edits that shouldn't have any noticeable impacts
Nothing player facing, its all minor fixes
=> [Modular] Fixes modular instances of mouse_opacity

_maps/map_files/VoidRaptor/VoidRaptor.dmm
The crystallizer always outputs south of it, which in this case was a wall, annoying!
I saw a fire alarm outside of cargo in space, I assume it was meant to be inside the forge room, so I put one in there, and added a firelock under the door so it actually does something.
atmosians don't need to move the crystallizer if they're producing stuff that doesn't like walls(supermatter shards)
The cargo foundry now has a fire alarm and firelock! Bitrunning has also received a firelock, they already had an alarm.
<details>
woaah, no more fire alarm in space
the crystallizer isn't facing a wall
</details>
:cl:
qol: The crystallizer in Void Raptor atmos has been moved very slightly so the recipes no longer spawn in the wall.
fix: The cargo foundry on Void …
=> Moves the crystallizer in void raptor atmos to not be facing a wall(and removes a fire alarm in space)

modular_nova/modules/ashwalkers/code/buildings/antfarm.dm, modular_nova/modules/ashwalkers/code/items/ash_seedmesh.dm, modular_nova/modules/primitive_cooking_additions/code/millstone.dm
Millstones no longer take damage when you insert something that has force (i.e. tower-cap logs) into them. Improves the feedback given by the millstone using balloon alerts when you insert items, and when you finish grinding.
Ant farms now drop the full amount of sand required to build them, when you try to build them in an invalid location. They now no longer accept food in them when ants have already appeared (because why would they?), and items inserted via plant bag usage is now two times faster (1/s -> 2/s).
Seed meshes now take 2 seconds to process 5 pieces of sand/ash instead of 5, and have a 50% chance of producing seeds, up from 30%. It's mainly to reduce the tedium of trying to obtain seeds from them, because they're otherwise a very niche and disappointing was to get seeds …
=> Fixes issues and improves millstones, ant farms and seed meshes

modular_nova/master_files/code/modules/client/preferences/headshot.dm
This PR changes the character headshot preference to allow for URLs via `files.byondhome.com`, which is Byond's built-in file uploader for Byond members only.
With the changes in this PR, players with a Byond membership can take advantage of their 20MB of hot-linkable online storage space for headshots. The file uploader can be accessed via logging into [Byond.com](https://www.byond.com/), then click "Manage Account" (https://secure.byond.com/members/-/account), then click "Files" in the top row.
See the circled link:
Tested locally ok!
<details>
</details>
:cl: A.C.M.O.
qol: Added support for adding Character Headshots via files.byondhome.com, for Byond members only.
/:cl:
=> [MODULAR] Character Headshots via files.byondhome.com

code/modules/deathmatch/deathmatch_lobby.dm, code/modules/mob/living/death.dm, modular_nova/master_files/code/modules/deathmatch/deathmatch_lobby.dm, modular_nova/master_files/code/modules/mob/living/carbon/death.dm, modular_nova/master_files/code/modules/mob/living/carbon/human/human.dm, modular_nova/modules/customization/modules/surgery/organs/genitals.dm, modular_nova/modules/interaction_menu/code/interaction_datum.dm, modular_nova/modules/modular_items/lewd_items/code/verbs.dm, tgstation.dme
Fixes https://github.com/NovaSector/NovaSector/issues/1260
Also cleans up some unrelated code. `mob/living/carbon/human/Initialize()` was needlessly overridden three times adding unnecessary overhead.
Fixes a bug/oversight.
<details>
</details>
:cl:
fix: synths gibbed in deathmatch do not drop their brains any longer
/:cl:
=> Fixes synths spilling brains when gibbed in deathmatch

_maps/map_files/NSVBlueshift/Blueshift.dmm
changed/fixed some things with blueshift,
removed misplaced windoors in or around science
gave the spare chambers around the supermatter an airalarm
changed a pipe under a plasma pressure tank in atmos, so that the pressure pump that was supposed to connect to the tank, didn't connect to the pipe under it
gave engineering a more visible RPD placement, along with the ones already in the radlockers
idk
<details>
new RPD placement
~~new wired APC~~ along with an airalarm
there isn't a windoor in these spots anymore
</details>
:cl:
fix: the misplaced windoors around science on blueshift are gone
qol: blueshift engineers have a more visible RPD placement for the supermatter
fix: the chambers surrounding the supermatter on blueshift have an accessible …
=> fixes some minor oddities in blueshift

_maps/RandomRuins/SpaceRuins/nova/piratefort.dmm, _maps/RandomRuins/SpaceRuins/nova/syndibase.dmm
Replaces some low pressure asteroid sand & reinforced floor on piratefort.dmm and syndiebase.dmm with airless versions
Roundstart active turfs bad
<details>
</details>
:cl:
fix: removed some roundstart active turfs from syndie outpost and pirate fort space ruin
/:cl:
=> Syndie Outpost & Pirate Fort AT Fix

_maps/shuttles/nova/slaver_syndie.dmm
All the pod floors of the slaver_syndie.dmm shuttle were varedited to have the default floor icon set it looks like, so I replaced them with unedited versions. Also replaced the microwave with the standard one, as the microwave icon it was pointing to was missing.
Cleaning up a shuttle map
<details>
</details>
:cl:
fix: removed some varedited turfs from the slaver syndie shuttle
/:cl:
=> Remove varedited floors from syndie slaver shuttle

modular_nova/modules/mentor/code/mentorhelp.dm, modular_nova/modules/mentor/code/mentorsay.dm, modular_nova/modules/verbs/code/looc.dm
Something about these verbs broke recently, not exactly where they broke but this small change restores them to functionality (Fixes #1496)
Things work as expected
<details>
</details>
:cl:
fix: MSAY, MENTORHELP, LOOC, and WALLPIERCE LOOC verbs all now work again
/:cl:
=> Fixes MSAY, MHELP, LOOC, and WALLPIERCE LOOC verbs

_maps/map_files/NSVBlueshift/Blueshift.dmm
The SMES in the grav room wasnt set to match other maps (why isnt a map helper made for this yet...) So i resolved that.
I also deleted 112 VV'd cameras and replaced them with proper ones
Gravity going out every single shift no matter what is kinda annoying, it gives pressure to engineers who may not be fully ready to 'rush' setting up an SM and given it happens before the 10 minute mark it's a bit cruel too.
<details>
Happy Engine
</details>
:cl:
qol: Blueshift - Gravity will now not go out in 10 minutes every shift-start
fix: Blueshift - Numerous non-template cameras in blueshift have been moved to autoname and replaces the VV'd ones
/:cl:
=> Blueshift - No more roundstart Gravity Blackouts

modular_nova/modules/contractor/code/datums/midround/event.dm
This variant (which only spawns one contractor at a time) was using the event system, which meant that it wasn't following the dynamic config.
This allows for proper control over an antag through dynamic.
I didn't want to spend two hours waiting for this to not run.
fix: Drifting Contractors now respects the dynamic config, by no longer running in the event system on top of the dynamic system.
/:cl:
=> Disables the Drifting Contractor random event in favor of using dynamic only to spawn them

modular_nova/modules/colony_fabricator/code/machines/power_storage_unit.dm, modular_nova/modules/colony_fabricator/code/machines/rtg.dm, modular_nova/modules/colony_fabricator/code/machines/stirling_generator.dm, modular_nova/modules/kahraman_equipment/code/ore_thumper.dm
I don't know why we should convert POWER to ENERGY to get correct amount of POWER in powernet. But it is what it is. Now sitrlings produce twice as much power and could do it's work in a new dark age of 1 MW loads of cell chargers.
Same problem happened to ore thumpers. Free ore is ended, they are once again eating theirs 50 kW as their description saying.
And while i'm at it, i have changed some plain numbers to TG defines increasing capacity of both flatpack SMESes. They are now back in line with regular SMESes: 15% for small battery and 2x for large.
Power generation machinery got their description changed slightly by adding new `display_power` proc. Nothing visually changed, but it is nice to have it this way.
Another fix for https://github.com/NovaSector/NovaSector/issues/1678 …
=> Power related fixes for flatpacked stirlings, ore thumpers and both sizes of station batteries

modular_nova/modules/colony_fabricator/code/appliances/chem_machines.dm, modular_nova/modules/colony_fabricator/code/appliances/wind_turbine.dm
I actually missed both of them in my previous PR, so here they are. I've changed recharge rate and consumption for coffee synthesizer a bit, because I can't remember how it used to work, but while testing locally, it seems to behave almost the same way as it were before. Also, I've upped wind turbine power gen by x2. Missed power-to-energy conversion here.
Sorry, no multicell chargers fixes as of now. I have no idea how to balance them without turning them in to low-cost power sinks.
more fixes
<details>
</details>
:cl:
fix: fixed wind turbines power generation and colony coffee machine taking literal ages to recharge
/:cl:
=> [no gbp] Some more colony machinery power related fiksiks (for wind generators and coffee synthesizer)

_maps/RandomRuins/LavaRuins/nova/lavaland_surface_interdyne_base1.dmm
Extending #1929 to Lavadyne, woo. Engineering gets a remap.
More QOL. Also fixes a couple small things here and there. Extra light switches, windows, etc.
<details>
</details>
:cl:
qol: lavadyne now has the micro reactor for power support.
/:cl:
=> Gives Lavadyne the new micro reactor

_maps/map_files/NSVBlueshift/Blueshift.dmm
Reworks distro and waste pipes in Blueshift's atmos mix/crystallizer room, as well as a few fluid ducts.
Also moved a vent so it is not hidden under a rack, and its operating status can be checked visually.
Having distro and waste run right through the center of atmos mixing rooms in generally a bad idea; there's a reason most maps don't do it. Even if a tech avoids layer 2/4, all it takes is one accidentally placed layer adapter and then you may end up with tritium or freon or so on in distro, or extremely hot plasma/o2/co2 clogging waste, and so on.
Experienced techs will know to rip up these pipes beforehand, but that's a pain, especially if there's already significant gases in distro or waste.
This change keeps the pipes to the borders of the room, reducing the chance for accidents …
=> Makes blueshift atmos mixing room friendly for gas mixing setups.

_maps/map_files/NSVBlueshift/Blueshift.dmm
This PR repositions the Blueshift's warden's office fire alarm (that was inside a display screen and couldn't be interacted with) and disables the bridge's spare ID card safe's density, making it possible to walk over it.
These were annoying me as much as they were annoying other players (and because it's really convenient).
<details>
</details>
:cl: Chelxox
qol: The Blueshift's warden's office fire alarm was repositioned so it can actually be interacted with.
qol: The bridge's spare ID safe on Blueshift can be walked on and doesn't block the path anymore.
/:cl:
=> Improving (very) small details on Blueshift

_maps/RandomRuins/SpaceRuins/nova/des_two.dmm, code/__DEFINES/~nova_defines/factions.dm, modular_nova/master_files/code/modules/mob_spawn/ghost_roles/mining_roles.dm, modular_nova/modules/mapping/code/interdyne_mining.dm, modular_nova/modules/mapping/code/mob_spawns.dm
Interdyne and DS2 have piggybacked off the Syndicate faction for a while and have had some unintended consequences as such. This just assigns the spawners their correct faction role that exists already as well as ensures everything behaves so the players aren't impacted at all.
I also adjusted the access to the control areas around the dock itself, this is aimed towards letting general DS2 crew be soloplay instead of having to hack the door open just to be able to go into the door/turn the turrets off.
I swapped the vault and the security post to facilitate this change without general interdyne crew being able to easily access the vault/unlock the shutters as well.
Security post shutters are now set to Leader
Some of our highest threat ruins are syndicate themed, and being able to walk in …
=> Ghost faction aligments

_maps/RandomRuins/SpaceRuins/nova/blackmarket.dmm, _maps/RandomRuins/SpaceRuins/nova/piratefort.dmm, _maps/RandomRuins/SpaceRuins/nova/syndibase.dmm, _maps/shuttles/nova/ruin_blackmarket_burst.dmm, _maps/shuttles/nova/ruin_interdyne_cargo.dmm
De-cheeses the pirate and syndibases so you have to complete the ruin to get the reward
I also removed the weird armory flag on all the crates in the pirate fort as it made zero sense for material ones
Fixed an AT on Blackmarket
Adjusted the difficulty of the syndicate outpost to also include better loot
like in my other balance passes, i'm firmly against an 'easy grab' of an extremely high tier loot, so being able to just take a wall down to grab a modsuit for example is ehhhhhhhh. 
The Syndie Outpost ruin always came across as lacking really any reward worth the risk, so i added an empty syndicate suit with the syndie storage module inside of a syndicrate that you need to crack the safe open to get the key (or think you can break it open and explode, your call). Note this type of suit …
=> Space Ruins - Balance/anti-cheese pass for PirateFort and Syndibase 

_maps/RandomRuins/LavaRuins/nova/lavaland_surface_interdyne_base1.dmm
The recent remap dropped the welding fuel tank from interdyne's engineering storage. This readds it.
Fixes missing equipment
<details>
</details>
:cl:
fix: Fixed missing fuel tank on interdyne after a previous remap
/:cl:
=> Fixes missing fuel tank on lavaland_surface_interdyne_base1.dmm

modular_nova/modules/autotransfer/code/transfer_vote.dm
A recent mirror broke transfer votes, now they're functional again.
Transfer votes working automatically is a good thing.
<details>
</details>
fix: Transfer votes will once again happen automatically.
/:cl:
=> Fixes transfer votes not working automatically

_maps/shuttles/nova/ruin_blackmarket_burst.dmm
Moved some layer 2 scrubbers to no longer be on the same tile as layer 2 pipes
Additionally moved the scrubber/vent in the control room to not be under the chair
All the messages about it in startup were driving me crazy
<details>
</details>
:cl:
fix: moved some scrubbers in the blackmarket shuttle to not be layered on top of same-layer pipes
/:cl:
=> Move some scrubbers in the Blackmarket Burst shuttle

_maps/RandomRuins/IceRuins/nova/icemoon_underground_icewalker_lower.dmm, _maps/nova/automapper/automapper_config.toml, _maps/nova/automapper/templates/icebox/icebox_ranch.dmm, _maps/nova/automapper/templates/mining/lavaland_ashwalker_fortress.dmm
the NTC ate the stock Ranch so this just adds one a bit lower
Birbs. But also cats and lizards get a tiny ranch to start off with plus one singular raptordex - until it's reskinned
<details>
</details>
:cl:
add: Added new mechanics or gameplay changes
add: Ranch to Icebox, Icecats and Ashwalkers
/:cl:
=> Adds Raptor Ranch to Icebox that NTC vore'd, Icecats and Ashies get a little one

modular_nova/modules/admin/code/player_ranks.dm, modular_nova/modules/lorecaster/code/story_manager.dm
Fixes: #2681 
Looks like the manage player ranks thing might not have been fully moved over to tg's new way of handling admin verbs as of https://github.com/NovaSector/NovaSector/pull/1950/files 
Edit: Lorecaster stories as well. 
Buttons should do the thing they are intended to.
<details>
</details>
:cl:
fix: manage player ranks & lorecaster stories buttons work again
/:cl:
=> Manage Player Ranks button fix

code/datums/components/lock_on_cursor.dm, code/game/turfs/turf.dm, code/modules/mob/living/carbon/alien/alien.dm, code/modules/shuttle/navigation_computer.dm
Tin. Just more uncovering of some of these image harddels. `blueprint_data` is a list of images.
I also went through the code and looked for any more instances of images being qdeleted that I could find.
Hard dels begone
:cl: vinylspiders
fix: fixes an /image harddel in station blueprints code: cleaned up some more /image qdels
/:cl:
=> [MISSED MIRROR] Fixes another image harddel in station blueprints (and more) (#80780)

modular_nova/modules/primitive_structures/code/fencing.dm, modular_nova/modules/primitive_structures/code/storage_structures.dm
I thought for sure this would've been an upstream issue
Turns out the bug was within us all along
you're going to have to trust me that these were, at some point, actually racks and railings
:cl:
fix: railings can be deconstructed
fix: racks can be deconstructed
/:cl:
=> Fix railing/rack deconstruction

code/modules/admin/view_variables/admin_delete.dm, code/modules/buildmode/submodes/advanced.dm, code/modules/buildmode/submodes/basic.dm, code/modules/buildmode/submodes/delete.dm, modular_nova/master_files/code/game/objects/effects/effect_system/effect_sparks.dm, tgstation.dme
Also cleans up and refactors the code to be a bit neater, and removes the possibility of having more than 20 of these particle effects running at a time. Should people be spamming it this should no longer be able to create lag.
Less accidental arson while in build mode for people who play with this enabled.
<details>
<summary>Working as before</summary>
</details>
:cl:
fix: the optional admin rainbow sparks (from item deletion) will no longer set things on fire
/:cl:
=> Stops admin item deletion sparks from setting everything on fire

code/modules/surgery/bodyparts/_bodyparts.dm
Tin. Peg limbs should be attachable with this quirk but they're not. Also adds feedback so it is clear why the limb is not able to be attached (if it's not robotic or peg).
Fixes a bug/oversight
<details>
<summary>Yarr it works</summary>
</details>
:cl:
fix: fixed an issue where peg limbs were not attachable to mobs with the "cybernetic limb mounts" quirk
/:cl:
=> Fixes peg limbs not being attachable to people with the Cybernetic Limb Mounts quirk

_maps/map_files/NSVBlueshift/Blueshift.dmm
Title.
I added these about two years ago. Blueshift was 3-Zs and we had arcing APCs. Couped with it being so massive. Blueshift had a *massive* energy draw and load. Today, with many of /tgs/ power refactors, the removal (I don't know if its removed, but I haven't seen it in ages) of arcing APCs, and of the handful of rounds I've came in to watch that were on Blueshift, the power stations seem to be insufficient.
Not to mention, I would commonly see these stations hot wired back to the main grid, which rendered them null.
I feel that their inclusion impacts nothing, and as such, decided to remove them.
<details>
</details>
:cl: Jolly
add: [Blueshift] Added more powernet redundancy as compensation. 
del: [Blueshift] There department power stations have …
=> [Blueshift] Removes the Power Stations

modular_nova/master_files/code/modules/research/techweb/all_nodes.dm
This PR just switches the cytology and wild harvest experiments from being a requirement, to giving a discount.
Makes the SAD a lot easier to unlock, no longer being locked behind the cytology experiment.
<details>
</details>
:cl:
qol: xenobiology research node no longer requires the cytology experiment; instead it gives a discount
qol: artificial selection research node no longer requires the wild harvest experiment; instead it gives a discount
/:cl
=> Xenobiology will no longer require the cytology experiment (instead it's a discount)

_maps/map_files/NSVBlueshift/Blueshift.dmm, _maps/map_files/VoidRaptor/VoidRaptor.dmm
Fixes engineering, telecoms access on Blueshift/VR to be consistent with other maps. Command access through to the server console. Construction to lobby. Removes paramedic access from Blueshift telecoms.
Consistent map access, Blueshift telecoms currently doesn't actually open for cards with only telecoms access.
:cl: LT3
fix: Fixed Blueshift and Void Raptor engineering/telecoms airlock access
fix: Telecomms Tech job trim now actually has access to Blueshift's telecomms
/:cl:
=> Fixes engi/tcomms access on Blueshift and Void Raptor

_maps/map_files/generic/CentCom_nova_z2.dmm
It's a snowflake code vendor that doesnt auto-assign offstation, so all i've done is toggle the offstation flag for it.
Murderous hotdog vending machines will no longer try to crush your face in the cafe, there's only one things we allow to do that.
<details>
</details>
:cl:
fix: Cafe's Hotdog vendor will no longer try to crush you
/:cl:
=> [NoGBP]Cafe's hotdog vendor can now hotdog less lethally than before.

code/datums/mutations/body.dm
Fixes https://github.com/NovaSector/NovaSector/issues/3192
The transform increase wasn't being reversed in `on_losing()` under certain conditions, resulting in a potential exploit where you could just keep increasing in size that way indefinitely.
Fixes a bug/exploit.
<details>
<summary>It works</summary>
</details>
:cl:
fix: fixes gigantism mutation not reducing a mob's size upon losing when it should be doing so.
/:cl:
=> Fixes a gigantism exploit

_maps/map_files/Birdshot/birdshot.dmm, code/game/turfs/open/floor/fancy_floor.dm
Revitalizing birdshot by extensively changing up most of the service departments.
Birdshot is in need of some changes. I was hoping that these changes would help improve it in the eyes of players.
This birdshot update features essentially an entirely moved/renovated service departments, along with an addition to an arcade and a commissary, along with a much improved public chapel. Moved the service lathe to a new service hall found between the kitchen and hydroponics. You can see the new layout below.
:cl:Viralmilk22
add: Shifted up the service departments on Birdshot.
add: Added an arcade.
/:cl:
=> [MANUAL MIRROR] - BirdShot Service Department Changes (#84080)

_maps/nova/automapper/automapper_config.toml, _maps/nova/automapper/templates/birdshot/birdshot_barber.dmm, _maps/nova/automapper/templates/birdshot/birdshot_ntrep_office.dmm
Title.
Birdshot already had a barbershop, so I moved it there.
As for the NTC office, I didn't like where it was, so I slid it over.
<details>
NTC Office
Barbershop
</details>
:cl: Jolly
fix: [Birdshot] There are no longer two barbershops on Birdshot.
del: [Birdshot] The NTC office is no longer next to the Captain's office, instead, its near the HoPs office!
/:cl:
=> [AutoMapper] Tweaks Birdshots NTC Office and Barbershop Templates

modular_nova/master_files/code/modules/shuttle/shuttle.dm, modular_nova/modules/alerts/code/alert_sound_to_playing.dm
They were far too loud, so I lowered them across the board to 50 instead of 70/80 (override_volume doesn't have sounds play even LOUDER either). The shuttles taking off and landing were also obnoxiously loud, so I made them falloff quicker.
Announcements have always been an ear-rape, now they're a little quieter. It's not perfect, and someone should probably go in those sound files and equalize them so they're not obnoxiously louder than they should be, but I figured I'd do something quick to make them better while I was still thinking about it.
Shuttles being so obnoxiously loud are what got me to turn off ship ambience in my prefs when they were introduced, I got them to lower to much more reasonable levels much faster so that it's not pure ear-rape anymore.
<details> …
=> Globally reduces the sound of announcements (including BSA and SM sounds), reduces the sound of the shuttles taking off and landing

.github/CODEOWNERS
I do a lot of work with map lints upstream, and I would like to keep an eye on them down here if I can.
Map lints impact maps but sometimes they can be a bit too restrictive, we want to avoid that, since being a downstream we have 0 way to satisfy issues on /tg/ maps.
=> Tweaks code owners + adds myself as a code owner to the maplints lint folder

modular_nova/modules/emote_panel/code/emote_panel.dm
https://github.com/NovaSector/NovaSector/blob/25887ec78016fe28095b0236379e1c02715ed81f/modular_nova/modules/emote_panel/code/emote_panel.dm#L235-L238
so yeah someone inverted a check when this was ported over
anyhow this should also be on the living checklist instead of the human checklist cause like, it applies to borgs and bots too and whatever.
Fixes #3923.
<details>
<summary>Human (No Robotic Voicebox)</summary>
</details>
<details>
<summary>Human (Yes Robotic Voicebox)</summary>
</details>
<details>
<summary>Synth</summary>
</details>
<details>
<summary>Borg</summary>
</details>
<details>
<summary>AI</summary>
</details>
<details>
<summary>Basic Bot</summary>
</details>
<details>
<summary>Simple Bot</summary>
</details>
<details>
<summary>Lisa the Corgi (For good measure)</summary> …
=> Fix synth/silicon emotes being missing from the emote panels for synths, bots, robotic voicebox users

_maps/map_files/SerenityStation/SerenityStation.dmm
Closes https://github.com/NovaSector/NovaSector/issues/3675
Closes https://github.com/NovaSector/NovaSector/issues/3920
Not sure how to go about the raptor skin issue since this map has both an icebox-like mining area and a lavaland (?)
Check changelog for more details
<details>
</details>
:cl: grungussuss
fix: Serenity station kitchen now has all fire safety-equipment
fix: Serenity station robotics stray decals have been removed
fix: Serenity station Arrivals Transport Airlocks now have correct unrestricted access
fix: Serenity station bridge maintenance has more redundancy
fix: Serenity station extra lightbulb in a bathroom stall has been removed
/:cl:
=> various mapping fixes for Serenity station

modular_nova/modules/customization/modules/mob/living/carbon/human/species/hemophage/_hemophage_defines.dm, modular_nova/modules/customization/modules/mob/living/carbon/human/species/hemophage/corrupted_tongue.dm, modular_nova/modules/customization/modules/mob/living/carbon/human/species/hemophage/hemophage_actions.dm, modular_nova/modules/customization/modules/mob/living/carbon/human/species/hemophage/hemophage_moods.dm, modular_nova/modules/customization/modules/mob/living/carbon/human/species/hemophage/hemophage_organs.dm, modular_nova/modules/customization/modules/mob/living/carbon/human/species/hemophage/hemophage_status_effects.dm, modular_nova/modules/customization/modules/mob/living/carbon/human/species/hemophage/hemophage_tumor.dm
Tweaked down a lot of numbers on Hemophages, being:
- Passive tumor blood drain: 0.125 u/s -> 0.05 u/s
- Tumor dormancy toggle cooldown: 3 minutes -> 2 minutes
- Dormant tumor speed multiplier: 3 -> 2 (they're moving faster when their tumor is dormant now).
- Blood consumed per 1 damage healed by the tumor: 1 u -> 0.25 u
- Maximum luminosity for healing: 0 -> 0.1 (they can regen with a little more light than before, it doesn't need to be PITCH BLACK anymore)
On top of that, Hemophages no longer get disgust or mood debuff from consuming synthetic blood, and their disgust from drinking from both Monkeys and Humonkeys are capped just like the disgust from eating regular food without Taste Suppressor.
On the topic of Taste Suppressor, you now get `TRAIT_AGEUSIA` when your tumor is dormant, …
=> Hemophage Balance Pass - Hemophages Suck Less Edition

modular_nova/modules/huds/code/glasses/HUD_Glasses.dm, modular_nova/modules/modular_items/code/modular_glasses.dm
fixes #3992
Huds were updated to use clothing traits, but prescription subtypes overwrite clothing traits to make them do prescription things.
(my bad)
i can't see without my glasses
<details>
(I just tested on live by VVing some glasses)
</details>
:cl:
fix: prescription huds work
/:cl:
=> Fixes prescription hud glasses

modular_nova/modules/primitive_structures/code/storage_structures.dm
https://github.com/NovaSector/NovaSector/pull/3928 messed with how smartfridges handle icons, so these needed updating to not be invisible. It did also add some easier customization, for non-fridgly smartfridges, like a less hacky way to disable floor-welding, so this makes sure we're up to date with all that. And makes them not have a vending noise, for whenever that comes back.
Also, allows produce displays to hold all sorts of flowers. Specifically by checking if it's an equippable item.
:ant:
<details>
https://github.com/user-attachments/assets/4fbbd79a-c348-44c7-967b-a371673f066f
</details>
:cl:
fix: produce bins & friends render properly
qol: produce displays can now hold all sorts of flowers
/:cl:
=> Fixes for primitive wooden storages

modular_nova/modules/emotes/code/synth_emotes.dm, modular_nova/modules/organs/code/tongue.dm
This pr applies some more polishing to the port of my pr, #3802, continuing from #3924.
First off, in the original pr we added `organ_traits = list(TRAIT_SILICON_EMOTES_ALLOWED)` to the robotic voicebox to allow users to use silicon emotes. The port, however, didn't account for our codebase _here_ having another robotic voicebox, the lizard robotic voicebox, that while functionally similar does not inherit this behaviour.
We simply add `organ_traits = list(TRAIT_SILICON_EMOTES_ALLOWED)` to this voicebox too, fixing that.
Then, we have the dwoop emote.
Before the port, our synth emotes here were actually inheritors of `/datum/emote/living/human`, with a typecache set to allow only humans and silicons, and then on each emote specifically checking for the synth species if it were a human. …
=> Polish the robotic voicebox silicon emotes refactor port

modular_nova/modules/icemoon_additions/code/icecat_recipes.dm
I was convinced I made the hearthkin armor inherit from the forged armor. Turns out it didn't. Woops!
Now the hearthkin can finally upgrade or imbue their armor. 
<details>
</details>
:cl: MortoSasye
fix: The Hearthkin's armor now inherits from the forged variety.
/:cl:
=> Fix: Hearthkin Armor now inherits from the forged armor

modular_nova/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
In #3887 there was an unintentional duplicate /obj/item/clothing/neck/padded/alt in the loadout menu, oops
Things not being broken = good
Game compiles and works good
:cl: Thedragmeme
fix: Fixes a duplicate item left by my donor PR and fixes a typo
/:cl:
=> [NO GBP] Fixes a stray extra item left by my donor PR and fixes the name of the feathered serenity dress in the loadout menu

modular_nova/master_files/code/modules/jobs/job_types/assistant/assistant.dm
They added a new assistant outfit, and unfortunately this behavior wasn't carried over, so now it is, and as such it should be fixed!
Seeing what pants you picked is pretty good for roleplay, I'd say. Less bugs == more better.
<details>
The pants are here! 
</details>
fix: Assistant jumpsuits/jumpskirts no longer override the undersuit loadout item in the character preview.
/:cl:
=> Fixes assistant loadout undersuit items being overridden by jumpsuits in the preview

code/controllers/subsystem/stock_market.dm
Really quick PR based on feedback from Discord (https://discord.com/channels/1171566433923239977/1172988592658841680/1265961618315935764).
This clamps the values that the GMM subsystem can set a material's price to a much, much narrower band. Previously, you could buy materials at a minimum value of 0.5x their base price and sell them for 3x their base price. I've changed this to have the minimum price be 95% and the maximum be 105% for a total of 10% ROI in the absolute best possible circumstances.
All this effectively does is slow down the arbitrage cycle. If you're increasing your investment by 5-10% every time you iterate an investment, your profit compounds quite significantly.
Follows up on https://github.com/NovaSector/NovaSector/pull/2498 to encourage people to use supplementary …
=> Clamp GMM resource values to minimize arbitrage

modular_nova/modules/primitive_production/code/glassblowing.dm
Tin, saw this in the logs and it bugged me. It does not change anything functionally, but it is better to not have the logs being polluted by garbage.
Less runtime log pollution with useless runtimes.
<details>
</details>
Nothing really player-facing
=> Fixes a glassblowing runtime

_maps/map_files/NSVBlueshift/Blueshift.dmm
Adds some missing air alarms on the engineering room with the shutters to the secure storage and transit tube.
Before
After
Transit tube
Before
After
Fixes some mapping oversights
Should be working fine
</details>
:cl: Hardly
fix: Adds missing air alarms in Blueshift's Engineering Room and Transit Tube
/:cl:
=> Adds missing air alarms on Blueshift engineering

_maps/nova/automapper/templates/icebox/icebox_ntrep_office.dmm
There is a sustenance vending machine in NT Rep's maintenance that currently does nothing without a valid prisoner ID, this PR gets rid of it.
Before
After
Fixes https://github.com/NovaSector/NovaSector/issues/4091
Removes what seems to be an oversight, considering that crew or prisoners can't really make use of that if you consider that it's several tiles away from the prison.
I opted against making an all-access version since it seems to be a bit too much work for an empty room for a map and would probably be better off done upstream.
Works, it's a pretty simple change.
:cl: Hardly
fix: Removes unusable sustenance machine in NT Rep's maintenance in Icebox Station
/:cl:
=> Removes unusable sustenance machine from NT Rep's maintenance in Icebox

_maps/map_files/Ouroboros/Ouroboros.dmm, config/maps.txt
Fixes and tweak stuff in Ouroboros to keep it consistent with other maps
-Laser tag banners no longer heal
-Flatpacker now starts as a flatpacking cube rather than pre-built, decal was kept intact as an indicator to build new machines on.
-Engineering lobby windoor rotated to north
-Adds a vent in engineering lobby
-Repipes the morgue, engineering guard post, dorms
-Changed the areas a bit in dorms
-Moved morgue APC from being on top of a morgue tray to somewhere else.
-Moved firelocks at engine room
-Moved a misplaced wall in maintenance
Makes Ouroboros better and more consistent with the other maps.
The reasoning for every change:
Banners are not meant to heal unless it's bussed by an admin.
Every other map starts with the flatpacker as a flatpack rather than pre-built.
Every other map …
=> Ouroboros fixes and tweaks

modular_nova/modules/loadouts/loadout_items/loadout_datum_shoes.dm
Closes https://github.com/NovaSector/NovaSector/issues/4389
Not really a big issue since you can rename things in the grand scheme of things, but this fixes name discrepancy potential. Just use the colorable version if you want to color them yourself.
Fixes an oversight.
<details>
</details>
:cl:
fix: specific-colored loadout sneakers no longer allow you to change greyscale colors (use the 'colorable' version for that)
/:cl:
=> Precolored sneakers no longer allow greyscale in loadout

code/modules/mob/mob.dm
It will only do that for mobs.
It was like that before I think?
<details>
</details>
:cl:
spellcheck: examining a mob will use an exclamation point after the thing's name, for everything else you get a period
/:cl:
=> Examine will no longer exclaim for everything

modular_nova/modules/ashwalkers/code/buildings/ash_clothing_vendor.dm, modular_nova/modules/faction/maps/shuttles/tradership_faction.dmm, modular_nova/modules/primitive_catgirls/code/clothing_vendor.dm
Tin. Updates a few vending machines that were hardcoded to manipulate `onstation` in ways that are no longer needed as of https://github.com/tgstation/tgstation/pull/86548.
Bugfix
<details>
</details>
:cl:
fix: fixed primitive 'vendors' (the ash clothing box and icecat wardrobe) costing money when they should be free
/:cl:
=> Primitive vending machines are free again

code/modules/reagents/chemistry/machinery/chem_dispenser.dm
This PR brings back saltpetre to upgraded chem dispensers. It's _meant to_ have saltpetre in upgraded dispensers, but a very-likely accidental omission since the days of the rodent made it so saltpetre was missing. I don't think it's gone for gameplay reasons, given how saltpetre is able to be made using 3 base ingredients that are already present. Base former(?)-upstream code has saltpetre in the list of upgraded reagents. If maintainers think this isn't a fix and was intended behavior then they can change the labels.
Also this changes the lists to have trailing commas as per the proper code style guide.
It kinda doesn't? It's a gameplay bug fix, not a roleplay addition. Still, bug fixes are nice and having saltpetre on demand is convenient for any advanced botanical needs.
<details> …
=> Brings back saltpetre to upgraded chem dispensers.

_maps/map_files/VoidRaptor/VoidRaptor.dmm
Solar SMES units were missing the wire underneath them. Fixed.
Max fixes, etc.
<details>
</details>
:cl:
fix: Void Raptor solar array SMES units are now properly connected to the grid.
/:cl:
=> Fixes Void Raptor solars

_maps/map_files/Snowglobe/snowglobe.dmm
This is a tiny patch to Snowglobe Station. 3 things in medbay are altered, 1 in cargo, 1 in sec.
-Both stasis beds now are in line of sight of the entrance. Before there was one bed near the waiting room, and one at the far wall. Now if two victims are dragged in at once, medics no longer have to arbitrarily elongate one patients suffering by dragging them across the bay.
-The front desk is changed from orderly to general now. Medical personnel really should be allowed to man the desk.
-Crew Monitoring and records console added to exam room. Before if you wanted to look up a medical record, you had to BREAK INTO THE FRONT DESK which is insane. I put an additional set so it's easier to make sure someone your about to treat doesn't require special considerations. 
-Cargo ORM reset to …
=> Snowglobe Nitpicks

_maps/RandomRuins/SpaceRuins/nova/blackmarket.dmm, modular_nova/modules/mapping/code/mob_spawns.dm
This one has been on my list for a few months but with the surgery n crap i just never got to it.
Simple:
Removes the two Alien tool spawns and replaces it with a single adv tool - i only ever meant for it to be 1 in the first place but the tools really should be find-only anyway.
Removes the Makarov and replaces it with a cycler - the Makarov's pretty powerful in its own sense, while it's also a perfectly fine starter weapon it kinda trivializes the role design too much. A cycler is just a stacked double barrel, sitting between a double barrel and the normal shotguns (max 4 inside vs 6 or 2 respectfully).
I made this role to be challenging, but i also gave it too many creature comforts in my last redesign so we're just dialing it back a little bit at a time until I'm happy with it. …
=> Space Ruin - Black Market Trader Balance pass

_maps/map_files/generic/CentCom_nova_z2.dmm
Adds Interdrobe to ghost cafe while removing the vine that is on red Secdrobe
Allows people to try out Interdyne's outfits without checking through chameleon's massive list, there was a subtype meant to be used for ghost cafe but it was never used anywhere.
The vine on the red Secdrobe was more annoying than anything, as you had to either break it or alt+click it in order to access the vending machine.
Works, also a very simple change.
<details>
</details>
:cl: Hardly
map: Added Interdrobe to the ghost cafe
map: Removed the vine on redsec's vendor in ghost cafe
/:cl:
=> Adds Interdrobe to ghost cafe and removes a certain vine from ghost cafe

_maps/RandomRuins/IceRuins/nova/icemoon_underground_interdyne_base1.dmm
Icebox Interdyne had an issue where their library was not connected to the powernet and had to be manually wired in.
This PR adds a single wire to fix it.
Fixes an oversight and allows the break room to be powered properly without having to wire it up every time.
It's a very simple fix. it works and should lint.
<details>
</details>
:cl: Hardly
fix: Icebox Interdyne's library is now connected with the powernet
/:cl:
=> Adds a missing wire next to Icebox Interdyne's library

_maps/map_files/Ouroboros/Ouroboros.dmm
Before
After
Lamps aren't meant to float
<details>
It's a pretty simple change that has no reason to fail at linting
</details>
:cl: Hardly
map: Ouroboros: Fixes a floating lamp in southern maintenance
/:cl:
=> Fixes floating lamp in Ouroboros maints

code/modules/mob/living/simple_animal/bot/secbot.dm
Reverts the changes made on #1832 , using the original TG values for beepsky.
Beepsky no longer checks for people weapons by default, so its not either automatically hitting people for having weapons they are permited to use anyways, unless security goes out of their way to unlock it and use beepsky that way.
Most of our crew uses weapons, its weird for this setting to had been specifically changed.
<details>
</details>
:cl:
qol: Beepsky no longer starts with the check weaponry setting on (so no more evil beepsky by default) (TG default)
/:cl:
=> Reverts #1832 - Beepsky doesnt check weapons by default anymore.

_maps/map_files/SerenityStation/SerenityStation.dmm
This PR does the following:
1. Makes mining bay accessible to all of cargo so they can access drone bay
2. Fixes a decal in cargo noclipping it's way into the walls
3. Fixes HoS ID painter by giving them the correct one (fixes https://github.com/NovaSector/NovaSector/issues/4597)
Lets cargo technicians access drone bay which is to the side of the mining bay while fixing other minor issues with the map
Compiled, should lint as well.
<details>
</details>
:cl: Hardly
fix: SerenityStation: Gave HoS the correct ID painter.
fix: SerenityStation: Fixed the decals in cargo creeping it's way into the walls.
map: Cargo Technicians can now access the drone bay without mining access.
/:cl:
=> SerenityStation patches

_maps/nova/automapper/automapper_config.toml, _maps/nova/automapper/templates/wawastation/wawastation_asteroidbluecell.dmm
Removes the rigged bluespace cell from wawa's asteroid area.
So I'm all for people not reading their surroundings and paying the consequences. The smokin' hot shower is a good example. There's a shower hooked up to a chem tank right next to a welding fuel tank, warning signs, etc.
... This little shit is just bait though. 
Automapper-ing it out.
<details>
</details>
:cl:
map: removed the trapped bluespace cell from wawa's asteroid area.
/:cl:
=> Removes the boobytrapped bluespace cell from Wawa's asteroid

modular_nova/modules/deforest_medical_items/code/storage_items.dm, modular_nova/modules/exp_corps/code/gear.dm
Right now this comes with the old vanguard ops field medic bonesaw. This is a `small` sized item with 20 force. This level of force is generally bulky+ size only. So let's tone that down a bit. 20 force -> 9 force via a new subtype.
Balancing.
<details>
</details>
:cl:
balance: medical technician kit's bonesaw is significantly less lethal now.
/:cl:
=> Med Technician Kit Balance Pass

modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm
They can wag again. Turns out that we were specifying which tail to use previously by setting it on the `/human` subtype, which `/cat` used to be a subtype of, but that got missed during the repathing.
<details>
</details>
fix: Felinids are no longer allergic to wagging their tails.
/:cl:
=> Fixes Felinid tail wagging

_maps/map_files/Ouroboros/Ouroboros.dmm
Brought up to me last night. There's a missing wire right outside of botany which makes power an issue for cargo/service. Fixes that, plus the dorms missing one. Also removes a couple of electrified grille spawners. 
QOL for engineers which have a hard enough time on this map.
<details>
</details>
:cl:
map: ouroboros has a slightly more robust powernet
/:cl:
=> Touches up Ouroboros's powernet.

modular_nova/modules/escape_menu/code/escape_menu_nova.dm
Fixes #4581 by moving our custom options down two notches
🖱️ 
<details>
</details>
:cl:
fix: The escape menu buttons no longer overlap
/:cl:
=> Fix escape menu spacing

code/modules/bitrunning/components/avatar_connection.dm
See https://github.com/tgstation/tgstation/pull/87879 for more information.
Tin; bitrunner names no longer override the crew manifest.
Fixes jank.
It's nicer to have the IDs use the actual names rather than being generic.
<details>
</details>
:cl: Stalkeos, 00-Steven
fix: A bitrunner avatar spawning with the exact same name as a name currently on the records no longer updates that record to match when the hacker alias gets applied.
qol: Net avatar ID cards use the net avatar's name instead of being generic.
/:cl:
=> Port of "Fix niche bitrunner avatar name bug and make net avatar ID take on avatar name" (but without TGS DMAPI)

code/modules/antagonists/changeling/powers/strained_muscles.dm, code/modules/movespeed/modifiers/innate.dm, modular_nova/master_files/code/modules/antagonists/changeling/changeling.dm
- Removes bonus genetic points, and the raised cap
- Nerfs the legbooster, as we run a lower movespeed already and it makes you go way-to-fast for anyone to catch
- cuts chemical regen to 1 every 2 seconds, instead of 1 per second, to see how it settles in the balance since there's a-lot of new powers.
rest untouched
prepping them for being readded
numbers change
:cl:
balance: Changeling has gone from 15 > 10 genetic points, had strained muscles heavily cutdown in the speedboost, and finally had it's chem-regen cut in half.
/:cl:
=> nerfs changeling to prepare for it being readded.

modular_nova/modules/horrorform/code/true_changeling.dm
title
presumed copypaste mistake in https://github.com/NovaSector/NovaSector/pull/3609/commits/47b431cb945cc98abdd317e82488b772485f57c9, which causes tomahawks to share the embed data of bone fragments.
fix
<details>
</details>
:cl:
fix: The bone fragments shot out by dying horrorform changelings have the correct embed chance. Same with the expedition tomahawk.
/:cl:
=> Fixes a typo in horrorform bone fragment embed datum

_maps/RandomRuins/IceRuins/nova/icemoon_underground_interdyne_base1.dmm
fixes https://github.com/NovaSector/NovaSector/issues/4562
<details>
</details>
:cl:
fix: The photocopier in Interdyne on icemoon is now free.
/:cl:
=> Icemoon Interdyne photocopier is now free to use

modular_nova/modules/opposing_force/code/opposing_force_datum.dm, tgui/packages/tgui/interfaces/OpposingForcePanel.jsx
i'm really running out of energy to write descriptive commit message
Fixes a tgui bluescreen from getting a NaN sent to the backend (due to lack of a `step` argument) which failed to get sanitized because the original argument was used instead of the sanitized one (and it also wasn't sanitized properly even if it was)
Fixes #4541
Fixes #4271
bugn't!
<details>
https://github.com/user-attachments/assets/10aa5024-b3a1-49a8-b7ae-e6e9a1ec612c
i hate how unresponsive (or incredibly oversensitive) these damn sliders are for small values but that's not my problem
</details>
:cl:
fix: OPFOR equipment quantity can now actually be adjusted
/:cl:
=> Fix OPFOR bluescreen

modular_nova/modules/window_airbags/code/window_airbag.dm
fixes https://github.com/NovaSector/NovaSector/issues/4595
<details>
</details>
:cl:
fix: Ghosts can no longer disarm window airbags.
/:cl:
=> Fixes disarming airbags as a ghost

modular_nova/modules/implants/code/medical_nodes.dm
tl;dr the + means it'll add to the list, instead of overwrite it
:cl:
fix: fixed the mining drill overwriting, instead of adding to the advanced mining node
/:cl:
=> fixes the mining drill (implant) addition removing all the other options in the adv_mining techtree addon

code/modules/surgery/organs/internal/eyes/_eyes.dm
[uuuh see title.](https://github.com/tgstation/tgstation/pull/88082)
eye explode through helmet probably suboptimal. deserved if you didn't have a helmet though
:cl: SmArtKar
balance: Armor now decreases the chances of getting your eye blown out by a rogue bullet
/:cl:
=> tg 88082 early port - armor helps against getting your eye exploded

modular_nova/modules/novaya_ert/code/surplus_armor.dm
It's drip or drown on this bitch an earth.
I don't think there's much to be said outside the usual 'more player customization is good, especially when the alternative is soft-white (for the jumpsuit) and 1 of 4 colors for the belts
<details>
</details>
:cl:
qol: The CIN outfit parts in the loadout can now be colored in said loadout.
/:cl:
=> sets the CIN jumpsuit, and belts to be recolorable in the loadout

modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
This PR fixes the Starfruit BBQ Meat Platter not consuming its crafting ingredients aside from the two roasted red peppers when it's made.
bugs are bad. max complexity food for the price of red peppers is probably also bad. also being unable to make it the best possible ribs on the planet is EVIL and i want to be THE RIB QUEEN
<details>
oh wow there's no ribs or glazed ribs left on the table how awesome
</details>
:cl:
fix: Fixed the starfruit BBQ platter failing to consume crafting ingredients.
/:cl:
=> Fixes the starfruit BBQ platter failing to consume crafting ingredients.

modular_nova/modules/contractor/code/items/modsuit/modsuit.dm
adds restraint assist and baton resistance modules to the contractor suit variants to bring them in-line with the other syndicate suits available to traitors
parity with other suits in a similar category of "you should just kill this guy if he has it"
:cl:
fix: For consistency's sake, Cybersun Industries has finally remembered to update their backlog of Contractor MODsuits with baton knockdown resistance and restraint assistance modules. Prospective operators are reminded that this will not stop them from being shot with disablers, or being shot in general.
/:cl:
=> gives contractor modsuits cuff assist + baton resist modules, comparable to traitor modsuits

code/modules/mob/living/carbon/alien/larva/powers.dm, code/modules/mob/living/carbon/human/human_defense.dm
In [this](https://github.com/NovaSector/NovaSector/pull/4307) it was forgotten to remove comments that remove some things related to xenomorphs. I just removed these comments
Xenomorphs are functional again
<details>
</details>
:cl:
fix: xenomorph larva can evolve again
/:cl:
=> xenomorph larva can evolve again

_maps/map_files/Snowglobe/snowglobe.dmm
Adds a stacking unit to Snowglobe's disposals. Somehow this has been missed repeatedly.
Missing. Fixed.
<details>
</details>
:cl:
map: Snowglobe - added stacking machine to disposals.
/:cl:
=> Snowglobe - Disposals Stacker

_maps/RandomRuins/IceRuins/nova/icemoon_underground_interdyne_base1.dmm
`all_products_free = 1`
Dyne doesn't get a paycheck. Needs to monch. Missed them in a previous pass.
<details>
</details>
:cl:
fix: icemoon's interdyne food vendors are free again
/:cl:
=> Fixes Icemoon Interdyne Food Vendors

modular_nova/master_files/code/modules/mob/basic/alien/_alien.dm
We override the base alien icon, but don't have an icon state for the xeno maid, so lets just don't
The people need their lusty ~~argonian~~ xenomorph maid
<details>
<summary>Screenshots/Videos</summary> 
</details>
:cl:
fix: Xenomorph maid has a sprite
/:cl:
=> Fixes xeno maid not having a sprite

code/modules/hydroponics/grown/cannabis.dm, modular_nova/modules/morenarcotics/code/thc.dm
So it came to my attention that hash creation does not work currently. You are supposed to be able to grind **dried** cannabis leaves using a mortar and pestle or reagent grinder but it fails to do so due to a bug.
The original code was trying to do some hackish stuff that no longer works with all the subsequent changes to grinding post-foodening. This PR just restores the ability to make this.
Some notes: You can still make hash from grinding dried mutated strains but it gets to be a bit silly with all the extra reagents that you get in your beaker or mortar. That cannot really be helped short of changing the way hash gets created but I do not really see it as an issue so much as just how produce grinding works. Another note: rainbow cannabis contains no thc so thus does not yield any …
=> Fixes a bug with hash grinding

.github/workflows/ci_suite.yml
Early Mirror of https://github.com/tgstation/tgstation/pull/88988
OpenDream was recently bumped to .NET 9, which is not on our runner image. I added an action which installs the required .NET version for DMCompiler to function.
Adding this action is not only good as a quick hack fix, but also for posterity.
I also considered the impact this has on our runner execution time, but my hope is that it should not matter if we have .NET installed already.
<details>
</details>
:cl:
code: Hopefully fixes opendream issues
/:cl:
=> [Early Mirror]Adds a .NET 9 SDK setup action to linters (#88988)

_maps/map_files/generic/CentCom_nova_z2.dmm
This PR adds the following to the ghost cafe:
- Replaces redundant crate near botany with service plumbing and hydroponics kits
- Replaces trays with T4s and optimizing them for plumbing
- Space cleaners on custodial room
- Torches to the entry and vendor part of the cave
- Fixes the nanotrasen logo looking a bit off, keeping it consistent with the decals you'd see across centcom and other maps
The service plumbing and the kit will be very useful for those who would like to make use of the cafe's botany without having to manually shove in the same nutriments over and over.
Cleaner is, obviously to keep the cafe clean as the janidrobe lacks any.
Torches, well, visibility's sake. Unless you know your way around the map it's a pain to get across places or the vendor. I personally want to see …
=> Minor QoL for Ghost Cafe

_maps/RandomRuins/SpaceRuins/nova/des_two.dmm
* Moves Syndie cargo boards to a table in the vault so they can be easily noticed and found
* Adds an autodrobe to DS-2 for fancy wears!
At occasional times on DS-2 I've wanted to have fancier clothing and attire but there was no autodrobe to do so! I think this would allow ds-2 members to have bit more fashion and glamour while operating on DS-2!
<details>
</details>
:cl:
map: moves DS-2 cargo boards to a table in the vault
map: adds an autodrobe to ds-2 dormitories
/:cl:
=> Minor alterations to DS-2

_maps/map_files/Snowglobe/snowglobe.dmm
Another tiny pr for Snowglobe. This one adds the ice cream machine and the food cart to the cafeteria. Also, a single chem bag in virology to save virologists a boring trip upstairs if they are in the zone.
Someone spent way too long looking for the ice cream machine only to find it did not exist. It really should exist. This PR makes it exist. Serendipitous. 
<details>
The ice cream and food cart in question.
polite roundstart bag to haul pills up to the public fridge for viro.
</details>
:cl:
add: Added Ice cream cart and Food Cart to Snowglobe. And a round start viro chem bag.
/:cl:
=> Snowglobe Ice Cream Machine

modular_nova/master_files/code/modules/mob/living/examine_tgui.dm, modular_nova/modules/character_directory/code/character_directory.dm, tgui/packages/tgui/interfaces/ExaminePanel.jsx, tgui/packages/tgui/interfaces/NovaCharacterDirectory.jsx
Tin.
Adds a way for players to more easily identify veteran crew players in game.
<details>
<summary>Seen in-game</summary>
</details>
:cl:
qol: adds veteran status to OOC notes in player panel + character directory
/:cl:
=> Adds veteran status to OOC notes in player panel + character directory

_maps/map_files/SerenityStation/SerenityStation.dmm
This, as the title may suggest, replaces a superfluous table in the lower level of SerenityStation's kitchen cold room with a cooking oil vat.
SerenityStation is the only map other than BirdShot, and the only map at all in Nova Sector's map rotation, that doesn't have a cooking oil vat in the cold room.
From what i can tell, the oil vat is more-or-less a standard fixture of the cold room, and its absence makes some things, like making beer batter for battered sausages, more difficult than they would be otherwise. It's theoretically possible to grind up soybean seeds for cooking oil, but i imagine people would rather get it from the vat, especially if they need large amounts.
<details>
</details>
:cl:
map: There is now a cooking oil vat in …
=> Adds a cooking oil vat to SerenityStation's cold room.

modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/underwear/undershirts.dm
Being forced to have these AS a bra sucks. What if I want a bra UNDER my fishnets? Huh? What about that punk?
Just adds an /undershirt/ version of the bra. That's it. That's the PR. 11 line change ~~(1 being a comment and 2 being whitespace so 8 functional lines)~~
This goes so hard feel free to screenshot
~~Makes me wish the fishnets weren't 100% opacity tbh. Feels a bit off.~~
:cl:
add: Added Undershirt variants of the greyscale Fishnets (for wearing OVER bras, as opposed to wearing them AS bras)
/:cl:
=> Adds an Undershirt version of the greyscale Fishnets

code/modules/power/supermatter/supermatter.dm
During a delam, ALL `/obj/machinery/power/supermatter_crystal` sent the signal to the suppression system.
Now only the Station's Supermatter should send the signal.
(`is_main_engine = TRUE` - _the only one that can have Slivers stolen and Cascade_)
A happy engineering team with a spontaneously-exploding supermatter is no longer a happy engineering team.
Off-station shard popped tf off
:cl:
fix: NT has sliiiightly tweaked the sensitivity of the Delamination Suppression System. It should no longer go off when there's a delamination in the range of 50,000 kilometers, instead only working around 500 meters.
/:cl:
=> Fixes non-primary SMs setting off the Delamination Suppression System

modular_nova/modules/ashwalkers/code/species/Ashwalkers.dm
Re-adds the examine text placed on ash walkers when they are and are not able to evolve now that evolution is based on status effects. These were the "Ashie has not yet reached the age for evolving." and "Ashie has reached the age for evolving!" messages. ~~It appears slightly higher in the examine text due to when status effects get checked but the examine messages are the same as they were previously.~~ There is no longer a difference in where it is rendered and is a direct re-add of the old messages and placements.
Being able to at a glance tell if your fellow ashwalkers were ready to evolve was around for a very long time and helpful to organizing the group without asking variations of 'are you ready?' frequently. Less time figuring out age timers means more time to interact in other …
=> re-add examinable effects for ashwalkers around evolutions.

modular_nova/modules/reagent_forging/code/crafting_bench.dm, modular_nova/modules/reagent_forging/code/crafting_bench_recipes.dm, modular_nova/modules/reagent_forging/code/forge_clothing.dm
Adds a variant of the chest armor using the icecats chainshirt icons as placeholder until someone better with sprites comes and offer an alternative.
Adds three tiers of armor values, Heavy, Medium and Light
The Plated armor and heartkin chainshirt uses heavy, the chainshirt and helmet uses medium, the gloves and boots use light values.
The amount of goliath/bear plates to upgrade each type changed, to 2 max for heavy and medium and 1 to light types. The effect of the upgrade no longer gives 10 melee extra armor, but 5 to melee, energy, laser, bullet, wounding and bomb.
This all results in an overall stronger armor, without the final armor reaching Drake set tier of melee protection.
It makes forged armor more unique, more balanced for the use outside of just being on the lavaland/ice …
=> [Balance] Forged armor pieces adjustments, made better all around, reduced grind.

modular_nova/master_files/code/game/objects/items/storage/belt.dm
Security belt currently has 7 slots instead of 5 and seemed to be unrestricted in what it could hold so I've changed our modular ``secbelt`` storage datum to instead make use of TG's existing ``security_belt`` storage datum while still keeping the gun belt restrictions in place.
Security webbings are unaffected.
Fixes what appears to be an oversight as regular security belts can usually only carry 5 security items at a time (with webbing carrying more)
<details>
</details>
:cl: Hardly
fix: fixes security belt so it has 5 slots and item restrictions again
/:cl:
=> Fixes security belt

modular_nova/modules/plexagon_selfserve/code/plexagon_selfserve.dm, modular_nova/modules/plexagon_selfserve/code/shamebox.dm
Fixes that clockout lockboxes were deleting themselves on creation (which also caused some terrible hard deletes) because we couldn't decide if they're abstract or not. Also refactors related code to use weakrefs or arguments instead of storing hard refs to ID cards.
fix
<details>
https://github.com/user-attachments/assets/e4fa73cf-2a6c-497a-8123-326d2fd3ac7e
</details>
:cl:
fix: Clocking out via PDA app now properly spawns lockboxes with restricted items
/:cl:
=> Fix clock-out lockboxes, refactor out uneeded hard references

modular_nova/modules/pet_owner/pet_owner.dm
Adds stoat as a selectable pet for the pet owner quirk.
There're stoats on station. You can take them home. They're free. I have 153 stoats living in my space garage.
People have fallen in love with the little guys since they've come on station, and I've seen a few crewmates tame the little fellows. This will allow for persistent stoat pets.
<details>
</details>
:cl:
add: Following NanoTrasen's recent introduction of stoats on station as a viable pest control solution, Central Command has found it fit to relax their customs policy to allow crewmates to bring stoats (rather obtained on station or through the intergalactic pet trade) through customs as part of their progressive Bring-Your-Pet-To-Work initiative.
/:cl:
=> Adds stoat to the list of pets selectable with pet owner

_maps/map_files/NSVBlueshift/Blueshift.dmm, _maps/map_files/Ouroboros/Ouroboros.dmm, _maps/map_files/SerenityStation/SerenityStation.dmm, _maps/map_files/Snowglobe/snowglobe.dmm, _maps/map_files/VoidRaptor/VoidRaptor.dmm
This adds in service guard lockers to the modular maps on Nova. Snowglobe gets one in its service post, Ouroboros in the bouncer's office, replacing the bouncer's cabinet, and Void Raptor, Blueshift, and Serenity all get them in the bar backroom/bar storage.
This pull request could be considered a sort of "first phase" in a two phase plan to add in service guard lockers to the maps. The second would be making mapping templates to add them to /tg/'s maps.
As of now, the only way to get a service guard locker on any map is to ahelp/pray to get one spawned in. While this would still be the case for a lot of maps in the rotation, i still think it's beneficial, because there would at least be five maps with service guard lockers, meaning that you wouldn't need to make a roundstart/post-init …
=> Adds in service guard lockers to Nova's maps.

_maps/nova/diorama/ash.dmm
Just changes every turf to be a fake version of said turf.
Fixes #5722
No more ATs
No player-facing changes.
=> Fixes Active Turfs in Interlink Ash Diorama

_maps/map_files/NSVBlueshift/Blueshift.dmm
A myriad of map fixes because it's a great map haunted by a lack of maintinence.
Before this is merged, if anybody knows of any other mapping issues on Blueshift, feel free to comment! Might as well get a few fixes in instead of just one! 
_(Issues that **DON'T** require a full rework. Small things, like the elevator, a missing light, a misplaced decal... Not solars. We all know about the solars.)_
<details><summary>Current list of changes:</summary>
- Fixes the Elevator Doors
- Fixes missing cable into Art Supply Storage
- Fixes missing cables to APC in Lesser Security Maintenance
- Adds APC to Quartermaster's Office
- Fixes a doubled wire in Engi Maints
- Fixes some incomplete pipes in Engi/Tcomms
- Removed Medbay's guaranteed power-cutoff mice trap (the mice room still exists right …
=> A bunch of Blueshift mapping fixes

modular_nova/modules/barricades/code/barricade.dm
Some weirdness and assumed oversight here, but i've just tweaked the armor values of the deployables.
Currently, for some reason. 2 iron rod guadrails were better overall than the cucks for armor - what. And had bio and fire 100?
They now match railings as railings cost 2 iron rods as well.
I also added some bomb resists to the barricade armor var, reducing it from bio 100 (??) to 80 and bumping up acid resist.
This just most likely is an oversight that wasn't noticed, didnt make sense for the guardrails to be so strong.
<details>
</details>
:cl:
balance: C.U.C.K.S. and co barriers are slightly better against bombs and acid, guardrails no longer are better than them and are balanced down to match the material resistances.
/:cl:
=> Deployable barricade balance

_maps/map_files/VoidRaptor/VoidRaptor.dmm
#5841 but voidraptor
This map respected the contraband poster-mainhall thing a lot more so those aren't really touched. Mostly just cleanup of stray decals and a few clunky rooms/pixelshifted objects. 
**Notably** I've removed lots of the gross unrepairable floors. Visually it's as similar as I could get it, but it's. Rebuildable now. So yay.
<details><summary>Comprehensive Changes</summary>
- Clean a few public-facing contraband Posters 
_(see #5841)_
- Retiles all of the AI Sat with normal tiles instead of irreparable Vault tiles
- Retiles all of AI Upload with normal tiles instead of irreparable Vault tiles
- Retiles the irreparable big space decals around the bridge with normal tiles
- Redoes Xenobio Freezer
_It was really jank. People keep needing to handbuild a holofan. It required …
=> Assorted Voidraptor map cleanup

_maps/virtual_domains/abductor_mothership.dmm
title says all. it was hidden under a pillow and i guess i just didn't notice it during my checking; reminder to self to check the compiled file when doing removals like this
i am making the on a limb assumption bitrunners should not have allcomms
<details>
</details>
:cl:
fix: Removed the last remaining Abductor Headset from Abductor Mothership. No more allcomms for bitrunners.
/:cl:
=> Fix a headset I missed in Abductor Mothership

_maps/map_files/Ouroboros/Ouroboros.dmm
Title
Gets rid of unintended stuff
I have not tested this at all but all I did was move the light from a tile to another.
<details>
</details>
:cl: Hardly
fix: The light switch in medical lobby is no longer on the floor.
/:cl:
=> Nukes the floor light switch from Ouroboros Medical Lobby
